### ISSUE TITLE
Download a build?

### ISSUE THREAD

**Issue by Codingale** [CivClassic/VanishNoPacket#1]
I'm looking for a 1.12.2 build for Paper (not sure if they're compatible)
and I can't get your POM to work. Help a homie out?

**Comment by Maxopoly** [comment]
Everything that works on spigot should also work on Paper.

[Here](https://mega.nz/file/4oJCUYzK#EhnMLSsSgfuekPlVwMLywIHnijQUF-Elh4AGlIh47e4 is a build I just made and i also fixed the pom so you should be able to build it yourself
